package entities;
// Generated Aug 23, 2017 1:22:01 PM by Hibernate Tools 5.2.3.Final


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatCoc generated by hbm2java
 */
@Entity
@Table(name = "DatCoc", catalog = "QuanLyKhachSan")
public class DatCoc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String maDc;
	private KhachHang khachHang;
	private Date ngayDat;
	private BigDecimal soTien;
	private String ghichu;
	private Boolean trangThai;

	public DatCoc() {
	}

	public DatCoc(String maDc, KhachHang khachHang) {
		this.maDc = maDc;
		this.khachHang = khachHang;
	}

	public DatCoc(String maDc, KhachHang khachHang, Date ngayDat, BigDecimal soTien, String ghichu,
			Boolean trangThai) {
		this.maDc = maDc;
		this.khachHang = khachHang;
		this.ngayDat = ngayDat;
		this.soTien = soTien;
		this.ghichu = ghichu;
		this.trangThai = trangThai;
	}

	@Id

	@Column(name = "MaDC", unique = true, nullable = false, length = 7)
	public String getMaDc() {
		return this.maDc;
	}

	public void setMaDc(String maDc) {
		this.maDc = maDc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAKH", nullable = false)
	public KhachHang getKhachHang() {
		return this.khachHang;
	}

	public void setKhachHang(KhachHang khachHang) {
		this.khachHang = khachHang;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NgayDat", length = 23)
	public Date getNgayDat() {
		return this.ngayDat;
	}

	public void setNgayDat(Date ngayDat) {
		this.ngayDat = ngayDat;
	}

	@Column(name = "SoTien", scale = 4)
	public BigDecimal getSoTien() {
		return this.soTien;
	}

	public void setSoTien(BigDecimal soTien) {
		this.soTien = soTien;
	}

	@Column(name = "Ghichu")
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@Column(name = "TrangThai")
	public Boolean getTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(Boolean trangThai) {
		this.trangThai = trangThai;
	}

}
