package entities;
// Generated Aug 23, 2017 1:22:01 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatPhong generated by hbm2java
 */
@Entity
@Table(name = "DatPhong", catalog = "QuanLyKhachSan")
public class DatPhong implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String maDp;
	private KhachHang khachHang;
	private LoaiPhong loaiPhong;
	private Date ngayDp;
	private Date ngayDen;
	private Date ngayDi;
	private int slNguoi;

	public DatPhong() {
	}

	public DatPhong(String maDp, KhachHang khachHang, LoaiPhong loaiPhong, Date ngayDp, Date ngayDen, Date ngayDi,
			int slNguoi) {
		this.maDp = maDp;
		this.khachHang = khachHang;
		this.loaiPhong = loaiPhong;
		this.ngayDp = ngayDp;
		this.ngayDen = ngayDen;
		this.ngayDi = ngayDi;
		this.slNguoi = slNguoi;
	}

	@Id

	@Column(name = "MaDP", unique = true, nullable = false, length = 7)
	public String getMaDp() {
		return this.maDp;
	}

	public void setMaDp(String maDp) {
		this.maDp = maDp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaKH", nullable = false)
	public KhachHang getKhachHang() {
		return this.khachHang;
	}

	public void setKhachHang(KhachHang khachHang) {
		this.khachHang = khachHang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaLoai", nullable = false)
	public LoaiPhong getLoaiPhong() {
		return this.loaiPhong;
	}

	public void setLoaiPhong(LoaiPhong loaiPhong) {
		this.loaiPhong = loaiPhong;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NgayDP", nullable = false, length = 23)
	public Date getNgayDp() {
		return this.ngayDp;
	}

	public void setNgayDp(Date ngayDp) {
		this.ngayDp = ngayDp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NgayDen", nullable = false, length = 23)
	public Date getNgayDen() {
		return this.ngayDen;
	}

	public void setNgayDen(Date ngayDen) {
		this.ngayDen = ngayDen;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NgayDi", nullable = false, length = 23)
	public Date getNgayDi() {
		return this.ngayDi;
	}

	public void setNgayDi(Date ngayDi) {
		this.ngayDi = ngayDi;
	}

	@Column(name = "slNguoi", nullable = false)
	public int getSlNguoi() {
		return this.slNguoi;
	}

	public void setSlNguoi(int slNguoi) {
		this.slNguoi = slNguoi;
	}

}
