package entities;
// Generated Aug 23, 2017 1:22:01 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * KhachHang generated by hbm2java
 */
@Entity
@Table(name = "KhachHang", catalog = "QuanLyKhachSan")
public class KhachHang implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String maKh;
	private TaiKhoan taiKhoan;
	private String hoTen;
	private boolean gioiTinh;
	private String diaChi;
	private String sdt;
	private String email;
	private String cmnd;
	private Set<DatPhong> datPhongs = new HashSet<DatPhong>(0);
	private Set<SuDungDv> suDungDvs = new HashSet<SuDungDv>(0);
	private Set<DatCoc> datCocs = new HashSet<DatCoc>(0);
	private Set<ThanhToan> thanhToans = new HashSet<ThanhToan>(0);

	public KhachHang() {
	}

	public KhachHang(String maKh, TaiKhoan taiKhoan, String hoTen, boolean gioiTinh, String diaChi,
			String sdt, String email, String cmnd) {
		this.maKh = maKh;
		this.taiKhoan = taiKhoan;
		this.hoTen = hoTen;
		this.gioiTinh = gioiTinh;
		this.diaChi = diaChi;
		this.sdt = sdt;
		this.email = email;
		this.cmnd = cmnd;
	}

	public KhachHang(String maKh, TaiKhoan taiKhoan, String hoTen, boolean gioiTinh, String diaChi,
			String sdt, String email, String cmnd, Set<DatPhong> datPhongs, Set<SuDungDv> suDungDvs,
			Set<DatCoc> datCocs, Set<ThanhToan> thanhToans) {
		this.maKh = maKh;
		this.taiKhoan = taiKhoan;
		this.hoTen = hoTen;
		this.gioiTinh = gioiTinh;
		this.diaChi = diaChi;
		this.sdt = sdt;
		this.email = email;
		this.cmnd = cmnd;
		this.datPhongs = datPhongs;
		this.suDungDvs = suDungDvs;
		this.datCocs = datCocs;
		this.thanhToans = thanhToans;
	}

	@Id

	@Column(name = "MaKH", unique = true, nullable = false, length = 7)
	public String getMaKh() {
		return this.maKh;
	}

	public void setMaKh(String maKh) {
		this.maKh = maKh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaTK", nullable = false)
	public TaiKhoan getTaiKhoan() {
		return this.taiKhoan;
	}

	public void setTaiKhoan(TaiKhoan taiKhoan) {
		this.taiKhoan = taiKhoan;
	}

	@Column(name = "HoTen", nullable = false)
	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	@Column(name = "GioiTinh", nullable = false)
	public boolean isGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(boolean gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "DiaChi", nullable = false)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "SDT", nullable = false, length = 11)
	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	@Column(name = "Email", nullable = false, length = 20)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "CMND", nullable = false, length = 15)
	public String getCmnd() {
		return this.cmnd;
	}

	public void setCmnd(String cmnd) {
		this.cmnd = cmnd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khachHang")
	public Set<DatPhong> getDatPhongs() {
		return this.datPhongs;
	}

	public void setDatPhongs(Set<DatPhong> datPhongs) {
		this.datPhongs = datPhongs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khachHang")
	public Set<SuDungDv> getSuDungDvs() {
		return this.suDungDvs;
	}

	public void setSuDungDvs(Set<SuDungDv> suDungDvs) {
		this.suDungDvs = suDungDvs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khachHang")
	public Set<DatCoc> getDatCocs() {
		return this.datCocs;
	}

	public void setDatCocs(Set<DatCoc> datCocs) {
		this.datCocs = datCocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khachHang")
	public Set<ThanhToan> getThanhToans() {
		return this.thanhToans;
	}

	public void setThanhToans(Set<ThanhToan> thanhToans) {
		this.thanhToans = thanhToans;
	}

}
