package entities;
// Generated Aug 23, 2017 1:22:01 PM by Hibernate Tools 5.2.3.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NhanVien generated by hbm2java
 */
@Entity
@Table(name = "NhanVien", catalog = "QuanLyKhachSan")
public class NhanVien implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String maNv;
	private TaiKhoan taiKhoan;
	private String hoTenNv;
	private boolean gioiTinh;
	private String diaChi;
	private String sdt;
	private String email;
	private Boolean trangThai;

	public NhanVien() {
	}

	public NhanVien(String maNv, TaiKhoan taiKhoan, String hoTenNv, boolean gioiTinh, String diaChi,
			String sdt, String email) {
		this.maNv = maNv;
		this.taiKhoan = taiKhoan;
		this.hoTenNv = hoTenNv;
		this.gioiTinh = gioiTinh;
		this.diaChi = diaChi;
		this.sdt = sdt;
		this.email = email;
	}

	public NhanVien(String maNv, TaiKhoan taiKhoan, String hoTenNv, boolean gioiTinh, String diaChi,
			String sdt, String email, Boolean trangThai) {
		this.maNv = maNv;
		this.taiKhoan = taiKhoan;
		this.hoTenNv = hoTenNv;
		this.gioiTinh = gioiTinh;
		this.diaChi = diaChi;
		this.sdt = sdt;
		this.email = email;
		this.trangThai = trangThai;
	}

	@Id

	@Column(name = "MaNV", unique = true, nullable = false, length = 7)
	public String getMaNv() {
		return this.maNv;
	}

	public void setMaNv(String maNv) {
		this.maNv = maNv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaTK", nullable = false)
	public TaiKhoan getTaiKhoan() {
		return this.taiKhoan;
	}

	public void setTaiKhoan(TaiKhoan taiKhoan) {
		this.taiKhoan = taiKhoan;
	}

	@Column(name = "HoTenNV", nullable = false)
	public String getHoTenNv() {
		return this.hoTenNv;
	}

	public void setHoTenNv(String hoTenNv) {
		this.hoTenNv = hoTenNv;
	}

	@Column(name = "GioiTinh", nullable = false)
	public boolean isGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(boolean gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "DiaChi", nullable = false)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "SDT", nullable = false, length = 11)
	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	@Column(name = "Email", nullable = false, length = 20)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "TrangThai")
	public Boolean getTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(Boolean trangThai) {
		this.trangThai = trangThai;
	}

}
