package entities;
// Generated Aug 23, 2017 1:22:01 PM by Hibernate Tools 5.2.3.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Phong generated by hbm2java
 */
@Entity
@Table(name = "Phong", catalog = "QuanLyKhachSan")
public class Phong implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String maPhong;
	private LoaiPhong loaiPhong;
	private String tenPhong;
	private String anh;
	private String gioithieu;
	private int slphong;
	private int slnguoi;
	private double gia;
	private String mota1;
	private String mota2;
	private String mota3;
	private String mota4;
	private String mota5;
	private String mota6;
	private String mota7;
	private String tienich1;
	private String tienich2;
	private String tienich3;
	private String tienich4;
	private String tienich5;
	private String tienich6;
	private String tienich7;
	private String tienich8;
	private String tienich9;
	private String tienich10;
	private Set<ThanhToan> thanhToans = new HashSet<ThanhToan>(0);

	public Phong() {
	}

	public Phong(String maPhong, LoaiPhong loaiPhong, String tenPhong, String anh, String gioithieu,
			int slphong, int slnguoi, double gia, String mota1, String mota2, String mota3,
			String mota4, String mota5, String mota6, String mota7, String tienich1,
			String tienich2, String tienich3, String tienich4, String tienich5,
			String tienich6, String tienich7, String tienich8, String tienich9,
			String tienich10) {
		this.maPhong = maPhong;
		this.loaiPhong = loaiPhong;
		this.tenPhong = tenPhong;
		this.anh = anh;
		this.gioithieu = gioithieu;
		this.slphong = slphong;
		this.slnguoi = slnguoi;
		this.gia = gia;
		this.mota1 = mota1;
		this.mota2 = mota2;
		this.mota3 = mota3;
		this.mota4 = mota4;
		this.mota5 = mota5;
		this.mota6 = mota6;
		this.mota7 = mota7;
		this.tienich1 = tienich1;
		this.tienich2 = tienich2;
		this.tienich3 = tienich3;
		this.tienich4 = tienich4;
		this.tienich5 = tienich5;
		this.tienich6 = tienich6;
		this.tienich7 = tienich7;
		this.tienich8 = tienich8;
		this.tienich9 = tienich9;
		this.tienich10 = tienich10;
	}

	public Phong(String maPhong, LoaiPhong loaiPhong, String tenPhong, String anh, String gioithieu,
			int slphong, int slnguoi, double gia, String mota1, String mota2, String mota3,
			String mota4, String mota5, String mota6, String mota7, String tienich1,
			String tienich2, String tienich3, String tienich4, String tienich5,
			String tienich6, String tienich7, String tienich8, String tienich9,
			String tienich10, Set<ThanhToan> thanhToans) {
		this.maPhong = maPhong;
		this.loaiPhong = loaiPhong;
		this.tenPhong = tenPhong;
		this.anh = anh;
		this.gioithieu = gioithieu;
		this.slphong = slphong;
		this.slnguoi = slnguoi;
		this.gia = gia;
		this.mota1 = mota1;
		this.mota2 = mota2;
		this.mota3 = mota3;
		this.mota4 = mota4;
		this.mota5 = mota5;
		this.mota6 = mota6;
		this.mota7 = mota7;
		this.tienich1 = tienich1;
		this.tienich2 = tienich2;
		this.tienich3 = tienich3;
		this.tienich4 = tienich4;
		this.tienich5 = tienich5;
		this.tienich6 = tienich6;
		this.tienich7 = tienich7;
		this.tienich8 = tienich8;
		this.tienich9 = tienich9;
		this.tienich10 = tienich10;
		this.thanhToans = thanhToans;
	}

	@Id

	@Column(name = "MaPhong", unique = true, nullable = false, length = 7)
	public String getMaPhong() {
		return this.maPhong;
	}

	public void setMaPhong(String maPhong) {
		this.maPhong = maPhong;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaLoai", nullable = false)
	public LoaiPhong getLoaiPhong() {
		return this.loaiPhong;
	}

	public void setLoaiPhong(LoaiPhong loaiPhong) {
		this.loaiPhong = loaiPhong;
	}

	@Column(name = "TenPhong", nullable = false)
	public String getTenPhong() {
		return this.tenPhong;
	}

	public void setTenPhong(String tenPhong) {
		this.tenPhong = tenPhong;
	}

	@Column(name = "Anh", nullable = false)
	public String getAnh() {
		return this.anh;
	}

	public void setAnh(String anh) {
		this.anh = anh;
	}

	@Column(name = "Gioithieu", nullable = false)
	public String getGioithieu() {
		return this.gioithieu;
	}

	public void setGioithieu(String gioithieu) {
		this.gioithieu = gioithieu;
	}

	@Column(name = "slphong", nullable = false)
	public int getSlphong() {
		return this.slphong;
	}

	public void setSlphong(int slphong) {
		this.slphong = slphong;
	}

	@Column(name = "slnguoi", nullable = false)
	public int getSlnguoi() {
		return this.slnguoi;
	}

	public void setSlnguoi(int slnguoi) {
		this.slnguoi = slnguoi;
	}

	@Column(name = "gia", nullable = false, precision = 53, scale = 0)
	public double getGia() {
		return this.gia;
	}

	public void setGia(double gia) {
		this.gia = gia;
	}

	@Column(name = "mota1", nullable = false)
	public String getMota1() {
		return this.mota1;
	}

	public void setMota1(String mota1) {
		this.mota1 = mota1;
	}

	@Column(name = "mota2", nullable = false)
	public String getMota2() {
		return this.mota2;
	}

	public void setMota2(String mota2) {
		this.mota2 = mota2;
	}

	@Column(name = "mota3", nullable = false)
	public String getMota3() {
		return this.mota3;
	}

	public void setMota3(String mota3) {
		this.mota3 = mota3;
	}

	@Column(name = "mota4", nullable = false)
	public String getMota4() {
		return this.mota4;
	}

	public void setMota4(String mota4) {
		this.mota4 = mota4;
	}

	@Column(name = "mota5", nullable = false)
	public String getMota5() {
		return this.mota5;
	}

	public void setMota5(String mota5) {
		this.mota5 = mota5;
	}

	@Column(name = "mota6", nullable = false)
	public String getMota6() {
		return this.mota6;
	}

	public void setMota6(String mota6) {
		this.mota6 = mota6;
	}

	@Column(name = "mota7", nullable = false)
	public String getMota7() {
		return this.mota7;
	}

	public void setMota7(String mota7) {
		this.mota7 = mota7;
	}

	@Column(name = "tienich1", nullable = false)
	public String getTienich1() {
		return this.tienich1;
	}

	public void setTienich1(String tienich1) {
		this.tienich1 = tienich1;
	}

	@Column(name = "tienich2", nullable = false)
	public String getTienich2() {
		return this.tienich2;
	}

	public void setTienich2(String tienich2) {
		this.tienich2 = tienich2;
	}

	@Column(name = "tienich3", nullable = false)
	public String getTienich3() {
		return this.tienich3;
	}

	public void setTienich3(String tienich3) {
		this.tienich3 = tienich3;
	}

	@Column(name = "tienich4", nullable = false)
	public String getTienich4() {
		return this.tienich4;
	}

	public void setTienich4(String tienich4) {
		this.tienich4 = tienich4;
	}

	@Column(name = "tienich5", nullable = false)
	public String getTienich5() {
		return this.tienich5;
	}

	public void setTienich5(String tienich5) {
		this.tienich5 = tienich5;
	}

	@Column(name = "tienich6", nullable = false)
	public String getTienich6() {
		return this.tienich6;
	}

	public void setTienich6(String tienich6) {
		this.tienich6 = tienich6;
	}

	@Column(name = "tienich7", nullable = false)
	public String getTienich7() {
		return this.tienich7;
	}

	public void setTienich7(String tienich7) {
		this.tienich7 = tienich7;
	}

	@Column(name = "tienich8", nullable = false)
	public String getTienich8() {
		return this.tienich8;
	}

	public void setTienich8(String tienich8) {
		this.tienich8 = tienich8;
	}

	@Column(name = "tienich9", nullable = false)
	public String getTienich9() {
		return this.tienich9;
	}

	public void setTienich9(String tienich9) {
		this.tienich9 = tienich9;
	}

	@Column(name = "tienich10", nullable = false)
	public String getTienich10() {
		return this.tienich10;
	}

	public void setTienich10(String tienich10) {
		this.tienich10 = tienich10;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phong")
	public Set<ThanhToan> getThanhToans() {
		return this.thanhToans;
	}

	public void setThanhToans(Set<ThanhToan> thanhToans) {
		this.thanhToans = thanhToans;
	}

}
