package entities;
// Generated Aug 23, 2017 1:22:01 PM by Hibernate Tools 5.2.3.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SuDungDv generated by hbm2java
 */
@Entity
@Table(name = "SuDungDV", catalog = "QuanLyKhachSan")
public class SuDungDv implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String maSddv;
	private DichVu dichVu;
	private KhachHang khachHang;
	private int soLuong;
	private int soNguoi;
	private double tongTien;
	private String ghiChu;
	private Set<ThanhToan> thanhToans = new HashSet<ThanhToan>(0);

	public SuDungDv() {
	}

	public SuDungDv(String maSddv, int soLuong, int soNguoi, double tongTien, String ghiChu) {
		this.maSddv = maSddv;
		this.soLuong = soLuong;
		this.soNguoi = soNguoi;
		this.tongTien = tongTien;
		this.ghiChu = ghiChu;
	}

	public SuDungDv(String maSddv, DichVu dichVu, KhachHang khachHang, int soLuong, int soNguoi, double tongTien,
			String ghiChu, Set<ThanhToan> thanhToans) {
		this.maSddv = maSddv;
		this.dichVu = dichVu;
		this.khachHang = khachHang;
		this.soLuong = soLuong;
		this.soNguoi = soNguoi;
		this.tongTien = tongTien;
		this.ghiChu = ghiChu;
		this.thanhToans = thanhToans;
	}

	@Id

	@Column(name = "MaSDDV", unique = true, nullable = false, length = 7)
	public String getMaSddv() {
		return this.maSddv;
	}

	public void setMaSddv(String maSddv) {
		this.maSddv = maSddv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaDV")
	public DichVu getDichVu() {
		return this.dichVu;
	}

	public void setDichVu(DichVu dichVu) {
		this.dichVu = dichVu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaKH")
	public KhachHang getKhachHang() {
		return this.khachHang;
	}

	public void setKhachHang(KhachHang khachHang) {
		this.khachHang = khachHang;
	}

	@Column(name = "SoLuong", nullable = false)
	public int getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(int soLuong) {
		this.soLuong = soLuong;
	}

	@Column(name = "SoNguoi", nullable = false)
	public int getSoNguoi() {
		return this.soNguoi;
	}

	public void setSoNguoi(int soNguoi) {
		this.soNguoi = soNguoi;
	}

	@Column(name = "TongTien", nullable = false, precision = 53, scale = 0)
	public double getTongTien() {
		return this.tongTien;
	}

	public void setTongTien(double tongTien) {
		this.tongTien = tongTien;
	}

	@Column(name = "GhiChu", nullable = false)
	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "suDungDv")
	public Set<ThanhToan> getThanhToans() {
		return this.thanhToans;
	}

	public void setThanhToans(Set<ThanhToan> thanhToans) {
		this.thanhToans = thanhToans;
	}

}
