package entities;
// Generated Aug 23, 2017 1:22:01 PM by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ThanhToan generated by hbm2java
 */
@Entity
@Table(name = "ThanhToan", catalog = "QuanLyKhachSan")
public class ThanhToan implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String maHd;
	private KhachHang khachHang;
	private Phong phong;
	private SuDungDv suDungDv;
	private Date ngayTt;
	private double tongTien;
	private String ghiChu;

	public ThanhToan() {
	}

	public ThanhToan(String maHd, Date ngayTt, double tongTien, String ghiChu) {
		this.maHd = maHd;
		this.ngayTt = ngayTt;
		this.tongTien = tongTien;
		this.ghiChu = ghiChu;
	}

	public ThanhToan(String maHd, KhachHang khachHang, Phong phong, SuDungDv suDungDv, Date ngayTt, double tongTien,
			String ghiChu) {
		this.maHd = maHd;
		this.khachHang = khachHang;
		this.phong = phong;
		this.suDungDv = suDungDv;
		this.ngayTt = ngayTt;
		this.tongTien = tongTien;
		this.ghiChu = ghiChu;
	}

	@Id

	@Column(name = "MaHD", unique = true, nullable = false, length = 7)
	public String getMaHd() {
		return this.maHd;
	}

	public void setMaHd(String maHd) {
		this.maHd = maHd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaKH")
	public KhachHang getKhachHang() {
		return this.khachHang;
	}

	public void setKhachHang(KhachHang khachHang) {
		this.khachHang = khachHang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaPhong")
	public Phong getPhong() {
		return this.phong;
	}

	public void setPhong(Phong phong) {
		this.phong = phong;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaSDDV")
	public SuDungDv getSuDungDv() {
		return this.suDungDv;
	}

	public void setSuDungDv(SuDungDv suDungDv) {
		this.suDungDv = suDungDv;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NgayTT", nullable = false, length = 23)
	public Date getNgayTt() {
		return this.ngayTt;
	}

	public void setNgayTt(Date ngayTt) {
		this.ngayTt = ngayTt;
	}

	@Column(name = "TongTien", nullable = false, precision = 53, scale = 0)
	public double getTongTien() {
		return this.tongTien;
	}

	public void setTongTien(double tongTien) {
		this.tongTien = tongTien;
	}

	@Column(name = "GhiChu", nullable = false)
	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

}
